name: scholarr_mobile_frontend
description: A new Flutter project.


publish_to: 'none' 
version: 1.1.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  provider: ^6.0.2
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  cached_network_image: ^3.2.0
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  import_sorter: ^4.6.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding_assets/
    - assets/menu_assets/

import_sorter:
  comments: false 